### ISSUE TITLE
Merge external wiki documentation into help browser

### ISSUE THREAD

**Issue by fire** [godot-extended-libraries/hydro#1]
Currently there's two places where documentation is stored, that is bad because it means duplicated work.

**Comment by jonri** [comment]
Is there a way to generate web-based documentation from the xml files?  I imagine that's how the official godot documentation is generated, but I'm not sure the best course of action for a module.  My original reasons for the duplication were:

1. So that users could easily see if the module might suit their needs before going to the trouble to build from source
2. Jumping to the documentation in-engine is nice, but when making heavy use of something new it can be more practical to keep the documentation in a separate window

I'll definitely roll the non-API documentation files into a proper readme, but I'd value some input on the above.

**Comment by fire** [comment]
Not sure. I would try asking Xrayez in the godot-extended-libraries for this feature in modules.

**Comment by jonri** [comment]
I ended up going down this rabbit hole myself.  It turns out that github supports .rst files in the wiki, which is the format that the xml documentation gets turned into for the official online docs.  I made a dedicated project to test the following workflow using Github Actions, which can automatically trigger anytime a commit changes a file in the doc_classes folder:

1. Check out the latest version of the repo
2. Grab the makerst.py tool from godot
3. Convert the .xml documentation to .rst
4. Run a sed script to fix up the links in the .rst files
5. Upload the .rst files to the wiki

With a handwritten main page and sidebar to pull it all together, this process could meet my goals of having web-based API documentation while also eliminating the manual duplication of those files.

**Comment by fire** [comment]
That sounds great. Feel free to add the feature.

**Comment by jonri** [comment]
Here's a summary of the documentation improvements:

- Any update to the doc_classes/ folder will automatically trigger Github Actions to regenerate the corresponding wiki page
- All remaining non-API documentation has been moved out of docs/ and into the wiki
- Main README.md points to the documentation in the wiki
