### ISSUE TITLE
Wiki has not been updated since 2020

### ISSUE THREAD

**Issue by fire** [godot-extended-libraries/hydro#21]
![image](https://github.com/godot-extended-libraries/hydro/assets/32321/28f8b82f-e5b0-4666-a107-1db6f05adb05)

```
Run mkdir .wiki
Checking for errors in the XML class reference...
ERROR: doc_classes/WaterArea3D.xml: "version" attribute missing from "doc".
ERROR: doc_classes/WatercraftPropulsion.xml: "version" attribute missing from "doc".
ERROR: doc_classes/HydroRigidBody.xml: "version" attribute missing from "doc".
ERROR: doc_classes/WatercraftBallast.xml: "version" attribute missing from "doc".
ERROR: doc_classes/WatercraftRudder.xml: "version" attribute missing from "doc".
Generating the RST class reference...

Generating the index file...

5 errors were found in the class reference XML. Please check the messages above.
Done```

**Comment by jonri** [comment]
Yes, this happened when you removed the "version" attribute in https://github.com/godot-extended-libraries/hydro/commit/bf6b7eb4ea59d3fa0901a100cfc8e5f491382ac9 ;-).  I've restored it and the wiki has regenerated, but it seems github isn't dealing with some of the markup correctly...

Once that's resolved I do need to update the pages that aren't automatically generated to point to the new class names.

**Comment by fire** [comment]
The newest version of Godot do not store versions in the xml.

https://github.com/godotengine/godot/blob/master/doc/classes/AABB.xml#L2

Not sure how to resolve.

**Comment by jonri** [comment]
In that case, the matching make_rst.py from the master branch probably needed to be used instead of the 4.1 version.  Unfortunately, all of the newer versions of make_rst come with a larger issue - they use annotations that github's markup parser does not support, leaving the wiki nearly unusable.

I reverted back to using the version of makerst.py from Godot 3.2 which generates much simpler output.  I checked the in-editor documentation using the master branch of godot and it doesn't seem to mind the extra version attribute still hanging around in the xml files.

I've updated the main page and sidebar to point to WaterArea3D instead of WaterArea as well.  Please let me know if you find any other docs that are out-of-date.
